# Generated by Django 3.2a1 on 2022-07-21 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_location', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='vehicle_images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('image2', models.ImageField(blank=True, null=True, upload_to='vehicle_images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('image3', models.ImageField(blank=True, null=True, upload_to='vehicle_images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('image4', models.ImageField(blank=True, null=True, upload_to='vehicle_images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('image5', models.ImageField(blank=True, null=True, upload_to='vehicle_images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('vehicle_model', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=5)),
                ('mileage', models.DecimalField(decimal_places=4, max_digits=10)),
                ('vin', models.CharField(max_length=17)),
                ('horsepower', models.IntegerField()),
                ('transmission', models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic')], default='manual', max_length=10)),
                ('door', models.IntegerField()),
                ('drive', models.CharField(choices=[('2', '2'), ('4', '4')], default='2', max_length=20)),
                ('seat', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10)),
                ('comment', models.TextField()),
                ('should_show', models.BooleanField(default=False)),
            ],
        ),
    ]
