# Generated by Django 3.2a1 on 2022-07-21 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user.user'),
        ),
        migrations.AddField(
            model_name='vehiclecomment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='admin_panel.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='admin_panel.branch'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='admin_panel.brand'),
        ),
    ]
