# Generated by Django 3.2a1 on 2022-07-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='sercive3',
            field=models.CharField(blank=True, default='...', max_length=70),
        ),
    ]
