# Generated by Django 3.2a1 on 2022-07-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_aboutus_sercive3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='sercive1',
            new_name='service1',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='sercive2',
            new_name='service2',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='sercive3',
            new_name='service3',
        ),
    ]
