# Generated by Django 3.2a1 on 2022-07-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pick_up_location',
            field=models.CharField(blank=True, max_length=500, verbose_name='Pick up Location (optional)'),
        ),
    ]
