# Generated by Django 3.2a1 on 2022-07-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_customerquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquery',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customerquery',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
