# Generated by Django 3.2a1 on 2022-07-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_alter_customerquery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='main_site.customerquery')),
            ],
        ),
    ]
