# Generated by Django 3.2a1 on 2022-07-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_auto_20220722_1240'),
        ('main_site', '0010_alter_faq_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='admin_panel.branch'),
        ),
    ]
